#
# This YAML file contains the configuration settings for the Mr-Nags chatbot.
# It defines the supported languages and their corresponding codes.
#
# Example usage:
#   - 'hi': Hindi
#   - 'en': English
#   - 'pa': Punjabi
#
languages:
  hi: Hindi
  en: English
  mr: Marathi

# Languages supported by Groq
# languages = {
#     "English": "English",
#     "हिन्दी": "Hindi",
#     "தமிழ்": "Tamil",
#     "తెలుగు": "Telugu",
#     "ಕನ್ನಡ": "Kannada",
#     "മലയാളം": "Malayalam",
#     "বাংলা": "Bengali",
#     "ગુજરાતી": "Gujarati",
#     "मराठी": "Marathi",
#     "ଓଡ଼ିଆ": "Oriya",
#     "ਪੰਜਾਬੀ": "Punjabi",
# }
